#!/bin/bash
set -e
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
pushd "$SCRIPT_DIR/UnitGen"
dotnet build
dotnet run
cd ..
jb cleanupcode --profile="Custom: Full Cleanup w/o Summary Comments" Jcd.Units.sln
cd ./Jcd.Units
dotnet build
cd ..
jb cleanupcode --profile="Custom: Full Cleanup w/o Summary Comments" Jcd.Units.sln
cd Jcd.Units.Examples
dotnet build
cd ../Jcd.Units.Tests
dotnet build
dotnet test
popd
