title: Jcd.Units
logo: assets/img/logo.jpg
description: <a href="/Jcd.Units" class="sitelink">Jcd.Units</a> — A unit-of-measure-bound-quantity library.
markdown: kramdown
show_downloads: false
google_analytics:
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
   - jekyll-remote-theme # add this line to the plugins list if you already have one
